const majors = [
    "Accounting",
    "Actuarial Science",
    "Administrative Leadership & Supervision in Education",
    "American Sign Language",
    "Animation",
    "Anthropology",
    "Applied Mathematics",
    "Architecture",
    "Art",
    "Art History",
    "Athletic Training",
    "Atmospheric Sciences",
    "Biochemistry",
    "Biological Sciences",
    "Biomedical Engineering",
    "Biomedical Sciences",
    "Biostatistics",
    "Chemistry",
    "Cinematic Arts",
    "Civil Engineering",
    "Classics",
    "Communication",
    "Comparative Literature",
    "Computer Engineering",
    "Computer Science",
    "Conservation & Environmental Science",
    "Criminal Justice",
    "Dance",
    "Data Analytics",
    "Data Science",
    "Design & Visual Communication",
    "Digital Arts",
    "Digital Supply Chain Management",
    "Economics",
    "Education",
    "Education Psychology",
    "Electrical Engineering",
    "English",
    "Environmental Engineering",
    "Film",
    "Film Studies",
    "Finance",
    "French",
    "General Business",
    "Geography",
    "Geosciences",
    "German",
    "Global Health",
    "Global Studies",
    "Health Care Administration",
    "History",
    "Human Resources Management",
    "Industrial Engineering",
    "Information Science & Technology",
    "International Studies",
    "Italian",
    "Jewish Studies",
    "Journalism",
    "Kinesiology",
    "Religious Studies"
]

export {majors}