const minors = [
    "Accounting",
    "Actuarial Science",
    "Administrative Leadership & Supervision in Education",
    "Anthropology",
    "Applied Mathematics",
    "Arabic Language and Literature",
    "Architecture",
    "Art",
    "Art History",
    "Atmospheric Sciences",
    "Biological Sciences",
    "Chemistry",
    "Classics",
    "Comparative Literature",
    "Computer Science",
    "Counseling",
    "Dance",
    "Economics",
    "Education",
    "Education Psychology",
    "Electrical Engineering",
    "English",
    "Environmental Engineering",
    "Film",
    "Film Studies",
    "Finance",
    "French",
    "General Business",
    "Geography",
    "Geosciences",
    "German",
    "Global Health",
    "Global Studies",
    "Health Care Administration",
    "History",
    "Human Resources Management",
    "Industrial Engineering",
    "Information Science & Technology",
    "International Studies",
    "Italian",
    "Japanese",
    "Jewish Studies",
    "Journalism",
    "Kinesiology",
    "Religious Studies",
    "Russian"
]

export {minors}